config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"
  resources :pocs
  devise_for :users
  post 'pocs/clear_flash' => 'pocs#clear_flash'

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :poc
  mount_uploader :file, DocumentUploader
end

app/models/language.rb
class Language < ActiveRecord::Base
  # Same language can be used in many language so there is many to many relationship between POC
  # and Language
  has_many :pocs_language
  has_many :pocs, through: :pocs_language
end

app/models/poc.rb
#
# This is the main model of the application. Poc means Proof of concept.  This model stores all data
# related to user's demo project having many documents and project source code as well.
#

class Poc < ActiveRecord::Base

  # This line will add tagging feature in this model
  acts_as_taggable

  mount_uploader :source_code, SourceCodeUploader

  #
  # Poc Relationships with other Modal
  #

  # POC has many documents
  has_many :documents, dependent: :destroy

  belongs_to :user
  # POC can be build using many languages and framework so here relationship between poc and language
  # is many to many
  has_many :pocs_language
  has_many :languages,  through: :pocs_language

  # Unable nested attributes for documents through POC
  accepts_nested_attributes_for :documents, allow_destroy: true

  #
  # Poc Model Validations
  #

  validates :name, presence: true, length: { maximum: 100}
  validates :source_code, presence: true
  validates :description, length: { maximum: 500 }
  validate :end_date_validations
  validate  :validate_future_end_date
  validate :validate_start_poc_at

  # Form datepicker returns mm.dd.yyyy so this method will parse and return proper sart_poc_at
  def start_poc_at=(val)
    write_attribute(:start_poc_at, Date.strptime(val, "%m/%d/%Y")) if val.present?
  end

  # Form datepicker returns mm.dd.yyyy so this method will parse and return proper end_poc_at
  def end_poc_at=(val)
    write_attribute(:end_poc_at, Date.strptime(val, "%m/%d/%Y")) if val.present?
  end

  # This is to verify that the start date is present or not if end date  is present
  def end_date_validations
    if end_poc_at.present?
      errors.add :base, "Please start date first!" unless start_poc_at.present?
    end
  end

  # End date must be greater than start date.
  def validate_future_end_date
    if end_poc_at.present? && start_poc_at.present?
      errors.add :base, "End date must be greater than start date!" if  start_poc_at > end_poc_at
    end
  end

  # This method checks that the start date is present or not if end date is not present
  def validate_start_poc_at
    if end_poc_at.present? && start_poc_at.nil?
      errors.add :base, "Start date must be present if end date is present"
    end
  end
end

app/models/pocs_language.rb
class PocsLanguage < ActiveRecord::Base
  # This class helpful for relationship between poc and language so it belongs to both POC and Language
  belongs_to :poc
  belongs_to :language
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pocs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/pocs_controller.rb
class PocsController < ApplicationController

  before_action :assign_poc, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def new
    @poc = current_user.pocs.build
  end

  def create
    @poc = current_user.pocs.new(poc_params.merge!(revision_number: 1, source_code: params[:poc][:source_code]))
    if @poc.save
      if params[:poc][:document] && params[:poc][:document][:file]
        params[:poc][:document][:file].each do |file|
          @poc.documents.create(file: file)
        end
      end
      flash[:success] = "POC added successfully."
      redirect_to pocs_path
    else
      flash[:error] = @poc.errors.full_messages
      render :new
    end
  end

  def index
    @pocs = current_user.pocs.includes(:languages, :tags)
  end

  def edit
  end

  def update
    new_revision_number = update_revision_number
    if @poc.update_attributes(poc_params.merge!(revision_number: new_revision_number))
      flash[:success] = "Poc details updated successfully."
      redirect_to pocs_path
    else
      flash[:danger] = @poc.errors.full_messages
      render :edit
    end
  end

  def show
    @poc = Poc.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    if @poc.destroy
      flash[:success] = "POC removed successfully"
    else
      flash[:danger] = "Unable to remove POC. Something went wrong."
    end
    redirect_to pocs_path
  end

  def clear_flash
    flash.clear
    @messages = nil
    @name = nil
    render nothing: true
  end
  private

  def assign_poc
    @poc ||= Poc.find(params[:id])
  end

  def poc_params
    params.require(:poc).permit(:name,
                                :start_poc_at,
                                :end_poc_at,
                                :description,
                                :revision_number,
                                :revision_note,
                                :key_features,
                                :tag_list,
                                :source_code,
                                documents: {}


    )
  end

  def update_revision_number
    @poc.revision_number += 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages_ad_type(flash)
    flash.each do |name, message|
      @messages = []
      @name = name
      if message.is_a?Array
        message.each do |msg|
          @messages << msg
        end
      else
        @messages << message
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pocs_helper.rb
module PocsHelper
end

app/views/home/index.html.haml
#modal-1.md-modal.md-effect-1
  .md-content
    %h3 Modal Dialog
    %div
      %p This is a modal window. You can do the following things with it:
      %ul
        %li
          %strong Read:
          modal windows will probably tell you something important so don't forget to read what they say.
        %li
          %strong Look:
          a modal window enjoys a certain kind of attention; just look at it and appreciate its presence.
        %li
          %strong Close:
          click on the button below to close the modal.
      .row
        %button.md-close Close me!
        %button.md-close.custom_save_popup_btn Close me!
.content-wrapper
  / Content Header (Page header)
  %section.content-header.clearfix
    .column
      %button.md-trigger{"data-modal" => "modal-1"} Fade in & Scale

app/views/layouts/_footer.html.haml
/ Main Footer
%footer.main-footer
  / To the right
  .pull-right.hidden-xs
    Knowledge-source-limited
  / Default to the left
  %strong
    Copyright © 2015
    = succeed "." do
      %a{:href => "#"} Knowledge-source Private Limited © 2015
  All rights reserved.

app/views/layouts/_header.html.haml
%header.main-header
  / Logo
  %a.logo{:href => "javascript:;"}
    %b> Knowledge-Source
  / Header Navbar
  %nav.navbar.navbar-static-top{:role => "navigation"}
    / Sidebar toggle button
    %a.sidebar-toggle{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
    / Navbar Right Menu
    .navbar-custom-menu
      %ul.nav.navbar-nav
        / Messages: style can be found in dropdown.less
        %li
          %a Membership
        %li
          %a FAQ
        %li
          = link_to "Logout",  destroy_user_session_path, method: :delete

app/views/layouts/_left_sidebar.html.haml
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar user panel (optional)
    .user-panel
      .pull-left.image
        %img.img-circle{:alt => "User Image", :src => "/assets/user2-160x160.jpg"}/
      .pull-left.info
        %p Alexander Pierce
        / Status
        %a{:href => "#"}
          %i.fa.fa-circle.text-success
          Online
    / search form (Optional)
    %form.sidebar-form{:action => "#", :method => "get"}
      .input-group
        %input.form-control{:name => "q", :placeholder => "Search...", :type => "text"}/
        %span.input-group-btn
          %button#search-btn.btn.btn-flat{:name => "search", :type => "submit"}
            %i.fa.fa-search
    / /.search form
    / Sidebar Menu
    %ul.sidebar-menu
      %li.header HEADER
      / Optionally, you can add icons to the links
      %li.active
        %a{:href => "#"}
          %span Link
      %li
        %a{:href => "#"}
          %span Another Link
      %li.treeview
        %a{:href => "#"}
          %span Multilevel
          %i.fa.fa-angle-left.pull-right
        %ul.treeview-menu
          %li
            %a{:href => "#"} Link in level 2
          %li
            %a{:href => "#"} Link in level 2

app/views/layouts/application.html.haml
!!!
%html.no-js{:lang => "en"}
  %head
    %title Knowledge-Source | Dashboard
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.skin-blue
    .wrapper
      - if user_signed_in?
        = render "layouts/header"
        = render "layouts/left_sidebar"
      = yield
      = render "layouts/footer"
      .md-overlay
%script{:src => "/assets/modalEffects.js"}
:javascript
  if("#{user_signed_in?}" == "false"){
    $("body.skin-blue").addClass("sidebar-collapse")
  }

app/views/pocs/_form.html.haml
= form_for @poc, html: {multipart: true } do |f|
  = render partial: 'shared/flash'
  / text input
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', placeholder: "Enter Name..."
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-calendar
      = f.text_field :start_poc_at, class: 'form-control', data: {provide:'datepicker'}
  .form-group
    .input-group
      .input-group-addon
        %i.fa.fa-calendar
      = f.text_field :end_poc_at, class: 'form-control', data: {provide:'datepicker'}
  / textarea
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control', placeholder: "Enter ..."
  .form-group
    = f.label :revision_note
    = f.text_area :revision_note, class: 'form-control', placeholder: "Enter ..."
  .form-group#someform
    = f.label :key_features
    %a#add_btn
      +
    %div#TextBoxDiv1
    = f.text_field :key_features, class: 'form-control', placeholder: "Enter ...", id: 'textbox1'
  .form-group
    = f.label :tag_list
    = f.text_field :tag_list, class: 'form-control', placeholder: "Enter ...", id: 'textbox1'
  .form-group
    = f.label :source_code
    = f.file_field :source_code

  = f.fields_for :document do |d|
    .form-group
      = d.label :file
      = d.file_field :file, multiple: true
  .form-group
    .box-footer
      = f.submit "Submit", class: 'btn btn-primary'

:javascript
  $(document).ready(function(){
    $('.datepicker').datepicker({
      format: "dd-mm-yyyy"
    });
  });

  $("#add_btn").click(function() {
      var template = "<input type='text' name='poc[key_features][INDEX]' value='' id='textbox[INDEX]' placeholder='Enter ...' class='form-control'>",
          index = $('text').length,
          compiled_template;
          compiled_textarea = $(template.replace("INDEX", index));
          $('#textbox'+index).append(compiled_textarea);
          index = index + 1;
  });

app/views/pocs/_poc_details.html.haml
.md-content
  %h3
    = poc.name
    %small
      = poc.status
  %div

    %p.tags.custom_margin
      %span.info-box-text
        %strong Technologies Used
      - poc.languages.each do |language|
        %a
          = language.name
    %p.tags.custom_margin
      %span.info-box-text
        %strong Tags
      - poc.tags.each do |tag|
        %a#label_tags
          = tag.name
    %p.languages_brief.custom_margin
      %span.info-box-text
        %strong
          Short Description
      = poc.description
    .custom_margin
      %span.info-box-text
        %strong
          Source Code
      %ul
        %li.source_file_name
          = poc.source_code.file.filename
        %li.source_link
          %a{:href => "#"}
            %img.download-btn{:src => "/assets/download_source.png"}
            %strong Download
    %p.custom_margin
      %span.info-box-text
        %strong
          Documents
      .box
        .box-body.no-padding
          %table.table.table-condensed
            %tbody
              %tr
                %th{:style => "width: 10px"} #
                %th Name
                %th Size
                %th{:style => "width: 40px"}
              %tr
                - poc.documents.each do |document|
                  %td 1.
                  %td
                    = document.file.file.filename
                  %td
                    20KB
                  %td
                    %a{:href => "#"}
                      %img.download-btn{:src => "/assets/download_source.png"}
    .row
      %button.md-close Got it!

:javascript
  $('.md-close').click(function(){
    $('#modal-1').removeClass("md-show")
  })

app/views/pocs/edit.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Edit POC
      %small Update your project
    / Main content
    %section.content
      .row
        / Your Page Content Here
        .col-md-3
        .col-md-6
          / general form elements disabled
          .box.box-warning
            .box-header
              %h3.box-title Edit Project
            / /.box-header
            .box-body
              = render 'pocs/form'

app/views/pocs/index.html.haml
.content-wrapper
  / Content Header (Page header)
  #modal-1.md-modal.md-effect-1
  %section.content-header
    %h1
      POCs
      %small Overview of POCs
  = render partial: 'shared/flash'
  %section.content
    .row
      .col-md-4.col-sm-6.col-xs-12
        .info-box
          %span.info-box-icon.bg-aqua
            %i.fa.fa-spinner.fa-spin
          .info-box-content
            %span.info-box-text In Progress
            %span.info-box-number
              90
              %small %
      .col-md-4.col-sm-6.col-xs-12
        .info-box
          %span.info-box-icon.bg-red
            %i.fa.fa-flag-checkered
          .info-box-content
            %span.info-box-text Finished
            %span.info-box-number 41,410
      .clearfix.visible-sm-block
      .col-md-4.col-sm-6.col-xs-12
        .info-box
          %span.info-box-icon.bg-green
            %i.fa.fa-hand-paper-o
          .info-box-content
            %span.info-box-text On Hold
            %span.info-box-number 760
    .row
      .col-md-4.col-sm-6.col-xs-12
        .info-box
          %span.info-box-icon.bg-aqua
            %i.ion.ion-ios-gear-outline
          .info-box-content
            %span.info-box-text Future Work
            %span.info-box-number
              90
              %small %
      .col-md-4.col-sm-6.col-xs-12
        .info-box
          %span.info-box-icon.bg-red
            %i.fa.fa-google-plus
          .info-box-content
            %span.info-box-text High Priority
            %span.info-box-number 41,410
      .clearfix.visible-sm-block
      .col-md-4.col-sm-6.col-xs-12
        .info-box
          %span.info-box-icon.bg-green
            %i.ion.ion-ios-cart-outline
          .info-box-content
            %span.info-box-text Low Priority
            %span.info-box-number 760

    .row
      .col-md-12
        %h3.timeline-header
          Available Projects
        .timeline-body
          - @pocs.each do |poc|
            %div.custom_div{:id => "#poc_div_#{poc.id}"}
              %h3.custom_margin
                = link_to poc.name, poc_path(poc), remote: true
                %small
                  = poc.status
              %span.custom_margin.info-box-text Technologies Used
              %p.tags.custom_margin
                - poc.languages.each do | language|
                  %a
                    = language.name
              %span.custom_margin.info-box-text Tags
              %p.tags.custom_margin
                - poc.tags.each do |tag|
                  %a#label_tags
                    = tag.name
  %section.content-header.clearfix
    .column
      = link_to "Call Show", "javascript:;", remote: true, id: "poc_div_2"
  .md-overlay
:javascript
  $('#poc_div_2').click(function(){
    $.ajax({
    url: '/pocs/1',
    method: 'GET'
    })
  })

app/views/pocs/new.html.haml
/ Content Wrapper. Contains page content
.content-wrapper
  / Content Header (Page header)
  %section.content-header
    %h1
      Add New POC
      %small Describe your project
    / Main content
    %section.content
      .row
        / Your Page Content Here
        .col-md-3
        .col-md-6
          / general form elements disabled
          .box.box-warning
            .box-header
              %h3.box-title New Project
            / /.box-header
            .box-body
              = render 'pocs/form'

app/views/pocs/show.js.haml
$("#modal-1").html('#{j render(partial: "pocs/poc_details", locals: {poc: @poc} )}');
$("#modal-1").addClass("md-show")

app/views/shared/_flash.html.haml
- unless flash.empty?
  .flash_msg.alert_msg
    - flash_messages_ad_type(flash)
  :javascript
    initialize_flash(#{@messages}, "#{@name}")

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider)
    %br/